// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5ruX05mPr6VyEhPJguN59b0svHgJjdCc',
    appId: '1:233341141393:web:f485741c3414885b58da30',
    messagingSenderId: '233341141393',
    projectId: 'k2x-assessment-task',
    authDomain: 'k2x-assessment-task.firebaseapp.com',
    storageBucket: 'k2x-assessment-task.appspot.com',
    measurementId: 'G-L8JG240NQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJxHLjor9P0E5Y5iP6BWZCJeMwkDMAmvw',
    appId: '1:233341141393:android:ca10bc55bf5e869358da30',
    messagingSenderId: '233341141393',
    projectId: 'k2x-assessment-task',
    storageBucket: 'k2x-assessment-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVAEOh2kn-PnGZa6uDSs2vCXQttkn3NAo',
    appId: '1:233341141393:ios:bb84527eb83f7a9d58da30',
    messagingSenderId: '233341141393',
    projectId: 'k2x-assessment-task',
    storageBucket: 'k2x-assessment-task.appspot.com',
    androidClientId: '233341141393-52nbr2kpn55hpp260gac4n501ike15j7.apps.googleusercontent.com',
    iosClientId: '233341141393-upgaam9bsgv0jib1ohn99t33qnhactuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.k2xAssessmentTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVAEOh2kn-PnGZa6uDSs2vCXQttkn3NAo',
    appId: '1:233341141393:ios:8d00bb3fd13d51ab58da30',
    messagingSenderId: '233341141393',
    projectId: 'k2x-assessment-task',
    storageBucket: 'k2x-assessment-task.appspot.com',
    androidClientId: '233341141393-52nbr2kpn55hpp260gac4n501ike15j7.apps.googleusercontent.com',
    iosClientId: '233341141393-1idlhhb346okhp07d0fveq7s5e8t54g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.k2xAssessmentTask.RunnerTests',
  );
}
